apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: mar11-testrag-ocp416
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar11-testrag-ocp416
  name: mar11-testrag-ocp416
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mar11-testrag-ocp416
    weight: 100
  wildcardPolicy: None
